"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Mahek Khandelwal, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:mk46782
UT EID 2:
"""



def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    substring= ""
    n = len(s)
    for i in range(n):
        char = set()
        for j in range(i, n):
            substring = s[i:j]
            for c in substring:
                if c in char:
                    pass
                else:
                    char.add(c)
        max_length = max(max_length, len(substring))
    return max_length

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    n = len(s)
    for i in range(n): 
        current_length = 0
        current = ""
        for j in range(i,n): 
            if(s[j] not in current):
                current += s[j]
                current_length +=1 
            else:
                break         
        max_length = max(max_length, current_length)  
    
    return max_length


    # max_length = 0
    # substring= ""
    # n = len(s)
    # for i in range(n):
    #     char = set()
    #     for j in range(i, n):
    #         substring = s[i:j]
    #         for c in substring:
    #             if c in char:
    #                 break
    #             else:
    #                 char.add(c)
    #     max_length = max(max_length, len(substring))
    # return max_length



def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    char = set()
    start = 0
    max_length = 0
    for i, c in enumerate(s):
        while c in char:
            char.remove(s[start])
            start +=1
        char.add(c)
        max_length = max(max_length, i-start +1)
    return max_length
