"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Mahek Khandelwal, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: mk46782
UT EID 2:
"""

class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    """Linked list class"""
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 3/24. If you choose to use
        # a dummy node, comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        """inserts term into linked list"""
        if coeff == 0:
            return
        new_node = Node(coeff, exp)
        if not self.head or self.head.exp < exp:
            new_node.next = self.head
            self.head = new_node
            return
        prev, curr = None, self.head

        while curr and curr.exp > exp:
            prev, curr = curr, curr.next
        if curr and curr.exp == exp:
            curr.coeff += coeff
            if curr.coeff == 0:
                if prev:
                    prev.next = curr.next
                else:
                    self.head = curr.next
                return
        new_node.next = curr
        if prev:
            prev.next = new_node
    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        """add polynomial p to the polynomial"""
        result = LinkedList()
        curr1, curr2 = self.head, p.head

        while curr1 or curr2:
            if curr1 and curr2:
                if curr1.exp > curr2.exp:
                    result.insert_term(curr1.coeff, curr1.exp)
                    curr1 = curr1.next
                elif curr2.exp> curr1.exp:
                    result.insert_term(curr2.coeff, curr2.exp)
                    curr2 = curr2.next
                else:
                    result.insert_term(curr1.coeff + curr2.coeff, curr1.exp)
                    curr1, curr2 = curr1.next, curr2.next
            elif curr1:
                result .insert_term(curr1.coeff, curr1.exp)
                curr1 = curr1.next
            else:
                result.insert_term(curr2.coeff, curr2.exp)
                curr2= curr2.next
        return result
# Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        """mulitply a polynomial p with the polynomial and 
        return the product as a new linked list"""
        result = LinkedList()
        curr1 = self.head
        while curr1:
            curr2 = p.head
            temp = LinkedList()
            while curr2:
                temp.insert_term(curr1.coeff *curr2.coeff, curr1.exp +curr2.exp)
                curr2 = curr2.next
            result = result.add(temp)
            curr1 = curr1.next
        return result
    # Return a string representation of the polynomial.
    def __str__(self):
        terms = []
        curr = self.head
        if not curr:
            return "0"
        while curr:
            if curr.coeff != 0:
                terms.append(f"({curr.coeff}, {curr.exp})")
            curr = curr.next
        return " + ".join(terms) if terms else "0"


def main():
    """read the data"""
    # read data from stdin (terminal/file) using input() and create polynomial p

    # read data from stdin (terminal/file) using input() and create polynomial q

    # get sum of p and q as a new linked list and print sum

    # get product of p and q as a new linked list and print product
    # Read first polynomial from stdin
    n = int(input())
    p = LinkedList()
    for _ in range(n):
        coeff, exp = map(int, input().split())
        p.insert_term(coeff, exp)
    input()
    m = int(input())
    q = LinkedList()
    for _ in range(m):
        coeff, exp = map(int, input().split())
        q.insert_term(coeff, exp)
    print(p.add(q))
    print(p.mult(q))


if __name__ == "__main__":
    main()
